### ISSUE TITLE
Responsive CSS

### ISSUE THREAD

**Issue by ghost** [links-js/links#1]
I don't know if this would help but, 
I've try to add some meta tags and it looks good.
I may make a PR if you want me to create this responsive interface.

**Comment by dogancelik** [comment]
Thanks for reporting, I'm working on it. Here's a preview.

![test](https://cloud.githubusercontent.com/assets/486818/14910342/059459c2-0df5-11e6-876b-2684a2ec96ab.gif)

**Comment by dogancelik** [comment]
I made some changes, please tell me what you think.

**Comment by ghost** [comment]
Looks absolutely amazing!
I think that's enough for a responsive site.

Oops.. , forget to tell you something,
Have you added a viewport to your meta tags?

**Comment by dogancelik** [comment]
Yeah I added the default viewport tag for Bootstrap. [ref](http://getbootstrap.com/css/#overview-mobile)

**Comment by ghost** [comment]
Ohh btw, I'm thinking about making the UI a little bit user-friendly using Flat-UI.
Let me know what you're thinking

**Comment by dogancelik** [comment]
I'm adding an input box for custom CSS, this way, you can customize the UI

Example CSS:

``` css
@import url(https://cdnjs.cloudflare.com/ajax/libs/flat-ui/2.3.0/css/flat-ui.min.css);
```

![aa](https://cloud.githubusercontent.com/assets/486818/14914712/6498dad6-0e15-11e6-8df8-851c21322f5c.jpg)
![aa2](https://cloud.githubusercontent.com/assets/486818/14914713/67102e2c-0e15-11e6-94ff-3fd2a853b7cf.jpg)

**Comment by ghost** [comment]
Eh.. I didn't quite understand, can you please explain me?✌🏻
And.. the `@import` in css is actually the same thing as `<link rel="stylesheet" href="file" />`

**Comment by dogancelik** [comment]
Yes, correct. Please [check here](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) if you want to learn more about it.

If you put the example CSS in Custom CSS box, you will get Flat UI.

**Comment by ghost** [comment]
No dude, I mean "this way, you can customize the UI".
What does that mean?

**Comment by dogancelik** [comment]
I meant that you can write a custom CSS so the page will look the way you want.
You can open Settings panel and write your custom CSS.

``` css
@import url(https://cdnjs.cloudflare.com/ajax/libs/flat-ui/2.3.0/css/flat-ui.min.css);
.tt-cursor, .tt-cursor .url, .tt-cursor .type i, .tt-cursor .tags,
.tt-suggestion:hover, .tt-suggestion:hover .url, .tt-suggestion:hover .type i, .tt-suggestion:hover .tags {
  color: #fff !important;
  background-color: rgb(72, 201, 176) !important;
}
```

![css](https://cloud.githubusercontent.com/assets/486818/14915786/36bd19f2-0e1e-11e6-8cf2-ada4a16285ca.jpg)
